/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminPaymentRequestsRouteImport } from './routes/admin.payment-requests'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTutorsRouteImport } from './routes/admin.tutors'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentPaymentsRouteImport } from './routes/parent.payments'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as StudentLessonsRouteImport } from './routes/student.lessons'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentRewardsRouteImport } from './routes/student.rewards'
import { Route as TutorDashboardRouteImport } from './routes/tutor.dashboard'
import { Route as TutorEarningsRouteImport } from './routes/tutor.earnings'
import { Route as TutorLessonsRouteImport } from './routes/tutor.lessons'
import { Route as TutorPaymentRequestsRouteImport } from './routes/tutor.payment-requests'
import { Route as AdminClassesIndexRouteImport } from './routes/admin.classes.index'
import { Route as AdminClassesIdRouteImport } from './routes/admin.classes.$id'
import { Route as ParentChildrenIdRouteImport } from './routes/parent.children.$id'
import { Route as ParentClassesIndexRouteImport } from './routes/parent.classes.index'
import { Route as ParentClassesIdRouteImport } from './routes/parent.classes.$id'
import { Route as TutorLessonIdIndexRouteImport } from './routes/tutor.lesson.$id.index'
import { Route as TutorLessonIdReviewRouteImport } from './routes/tutor.lesson.$id.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentRequestsRoute = AdminPaymentRequestsRouteImport.update({
  id: '/admin/payment-requests',
  path: '/admin/payment-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorsRoute = AdminTutorsRouteImport.update({
  id: '/admin/tutors',
  path: '/admin/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentPaymentsRoute = ParentPaymentsRouteImport.update({
  id: '/parent/payments',
  path: '/parent/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/student/homework',
  path: '/student/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLessonsRoute = StudentLessonsRouteImport.update({
  id: '/student/lessons',
  path: '/student/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/student/progress',
  path: '/student/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRewardsRoute = StudentRewardsRouteImport.update({
  id: '/student/rewards',
  path: '/student/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorDashboardRoute = TutorDashboardRouteImport.update({
  id: '/tutor/dashboard',
  path: '/tutor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorEarningsRoute = TutorEarningsRouteImport.update({
  id: '/tutor/earnings',
  path: '/tutor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorLessonsRoute = TutorLessonsRouteImport.update({
  id: '/tutor/lessons',
  path: '/tutor/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorPaymentRequestsRoute = TutorPaymentRequestsRouteImport.update({
  id: '/tutor/payment-requests',
  path: '/tutor/payment-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesIndexRoute = AdminClassesIndexRouteImport.update({
  id: '/admin/classes/',
  path: '/admin/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassesIdRoute = AdminClassesIdRouteImport.update({
  id: '/admin/classes/$id',
  path: '/admin/classes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenIdRoute = ParentChildrenIdRouteImport.update({
  id: '/parent/children/$id',
  path: '/parent/children/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentClassesIndexRoute = ParentClassesIndexRouteImport.update({
  id: '/parent/classes/',
  path: '/parent/classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentClassesIdRoute = ParentClassesIdRouteImport.update({
  id: '/parent/classes/$id',
  path: '/parent/classes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorLessonIdIndexRoute = TutorLessonIdIndexRouteImport.update({
  id: '/tutor/lesson/$id/',
  path: '/tutor/lesson/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorLessonIdReviewRoute = TutorLessonIdReviewRouteImport.update({
  id: '/tutor/lesson/$id/review',
  path: '/tutor/lesson/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tutors': typeof AdminTutorsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/payments': typeof ParentPaymentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/lessons': typeof TutorLessonsRoute
  '/tutor/payment-requests': typeof TutorPaymentRequestsRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/parent/classes/': typeof ParentClassesIndexRoute
  '/tutor/lesson/$id/review': typeof TutorLessonIdReviewRoute
  '/tutor/lesson/$id/': typeof TutorLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tutors': typeof AdminTutorsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/payments': typeof ParentPaymentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/lessons': typeof TutorLessonsRoute
  '/tutor/payment-requests': typeof TutorPaymentRequestsRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/admin/classes': typeof AdminClassesIndexRoute
  '/parent/classes': typeof ParentClassesIndexRoute
  '/tutor/lesson/$id/review': typeof TutorLessonIdReviewRoute
  '/tutor/lesson/$id': typeof TutorLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/payment-requests': typeof AdminPaymentRequestsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tutors': typeof AdminTutorsRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/payments': typeof ParentPaymentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/rewards': typeof StudentRewardsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/lessons': typeof TutorLessonsRoute
  '/tutor/payment-requests': typeof TutorPaymentRequestsRoute
  '/admin/classes/$id': typeof AdminClassesIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/classes/$id': typeof ParentClassesIdRoute
  '/admin/classes/': typeof AdminClassesIndexRoute
  '/parent/classes/': typeof ParentClassesIndexRoute
  '/tutor/lesson/$id/review': typeof TutorLessonIdReviewRoute
  '/tutor/lesson/$id/': typeof TutorLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/operations'
    | '/admin/payment-requests'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/tutors'
    | '/parent/dashboard'
    | '/parent/payments'
    | '/student/dashboard'
    | '/student/homework'
    | '/student/lessons'
    | '/student/progress'
    | '/student/rewards'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/lessons'
    | '/tutor/payment-requests'
    | '/admin/classes/$id'
    | '/parent/children/$id'
    | '/parent/classes/$id'
    | '/admin/classes/'
    | '/parent/classes/'
    | '/tutor/lesson/$id/review'
    | '/tutor/lesson/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/operations'
    | '/admin/payment-requests'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/tutors'
    | '/parent/dashboard'
    | '/parent/payments'
    | '/student/dashboard'
    | '/student/homework'
    | '/student/lessons'
    | '/student/progress'
    | '/student/rewards'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/lessons'
    | '/tutor/payment-requests'
    | '/admin/classes/$id'
    | '/parent/children/$id'
    | '/parent/classes/$id'
    | '/admin/classes'
    | '/parent/classes'
    | '/tutor/lesson/$id/review'
    | '/tutor/lesson/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/operations'
    | '/admin/payment-requests'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/tutors'
    | '/parent/dashboard'
    | '/parent/payments'
    | '/student/dashboard'
    | '/student/homework'
    | '/student/lessons'
    | '/student/progress'
    | '/student/rewards'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/lessons'
    | '/tutor/payment-requests'
    | '/admin/classes/$id'
    | '/parent/children/$id'
    | '/parent/classes/$id'
    | '/admin/classes/'
    | '/parent/classes/'
    | '/tutor/lesson/$id/review'
    | '/tutor/lesson/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPaymentRequestsRoute: typeof AdminPaymentRequestsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTutorsRoute: typeof AdminTutorsRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentPaymentsRoute: typeof ParentPaymentsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentLessonsRoute: typeof StudentLessonsRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentRewardsRoute: typeof StudentRewardsRoute
  TutorDashboardRoute: typeof TutorDashboardRoute
  TutorEarningsRoute: typeof TutorEarningsRoute
  TutorLessonsRoute: typeof TutorLessonsRoute
  TutorPaymentRequestsRoute: typeof TutorPaymentRequestsRoute
  AdminClassesIdRoute: typeof AdminClassesIdRoute
  ParentChildrenIdRoute: typeof ParentChildrenIdRoute
  ParentClassesIdRoute: typeof ParentClassesIdRoute
  AdminClassesIndexRoute: typeof AdminClassesIndexRoute
  ParentClassesIndexRoute: typeof ParentClassesIndexRoute
  TutorLessonIdReviewRoute: typeof TutorLessonIdReviewRoute
  TutorLessonIdIndexRoute: typeof TutorLessonIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-requests': {
      id: '/admin/payment-requests'
      path: '/admin/payment-requests'
      fullPath: '/admin/payment-requests'
      preLoaderRoute: typeof AdminPaymentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutors': {
      id: '/admin/tutors'
      path: '/admin/tutors'
      fullPath: '/admin/tutors'
      preLoaderRoute: typeof AdminTutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/payments': {
      id: '/parent/payments'
      path: '/parent/payments'
      fullPath: '/parent/payments'
      preLoaderRoute: typeof ParentPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/student/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/lessons': {
      id: '/student/lessons'
      path: '/student/lessons'
      fullPath: '/student/lessons'
      preLoaderRoute: typeof StudentLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/student/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/rewards': {
      id: '/student/rewards'
      path: '/student/rewards'
      fullPath: '/student/rewards'
      preLoaderRoute: typeof StudentRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/dashboard': {
      id: '/tutor/dashboard'
      path: '/tutor/dashboard'
      fullPath: '/tutor/dashboard'
      preLoaderRoute: typeof TutorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/earnings': {
      id: '/tutor/earnings'
      path: '/tutor/earnings'
      fullPath: '/tutor/earnings'
      preLoaderRoute: typeof TutorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/lessons': {
      id: '/tutor/lessons'
      path: '/tutor/lessons'
      fullPath: '/tutor/lessons'
      preLoaderRoute: typeof TutorLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/payment-requests': {
      id: '/tutor/payment-requests'
      path: '/tutor/payment-requests'
      fullPath: '/tutor/payment-requests'
      preLoaderRoute: typeof TutorPaymentRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/': {
      id: '/admin/classes/'
      path: '/admin/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AdminClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classes/$id': {
      id: '/admin/classes/$id'
      path: '/admin/classes/$id'
      fullPath: '/admin/classes/$id'
      preLoaderRoute: typeof AdminClassesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children/$id': {
      id: '/parent/children/$id'
      path: '/parent/children/$id'
      fullPath: '/parent/children/$id'
      preLoaderRoute: typeof ParentChildrenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/classes/': {
      id: '/parent/classes/'
      path: '/parent/classes'
      fullPath: '/parent/classes/'
      preLoaderRoute: typeof ParentClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/classes/$id': {
      id: '/parent/classes/$id'
      path: '/parent/classes/$id'
      fullPath: '/parent/classes/$id'
      preLoaderRoute: typeof ParentClassesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/lesson/$id/': {
      id: '/tutor/lesson/$id/'
      path: '/tutor/lesson/$id'
      fullPath: '/tutor/lesson/$id/'
      preLoaderRoute: typeof TutorLessonIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/lesson/$id/review': {
      id: '/tutor/lesson/$id/review'
      path: '/tutor/lesson/$id/review'
      fullPath: '/tutor/lesson/$id/review'
      preLoaderRoute: typeof TutorLessonIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPaymentRequestsRoute: AdminPaymentRequestsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTutorsRoute: AdminTutorsRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentPaymentsRoute: ParentPaymentsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentLessonsRoute: StudentLessonsRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentRewardsRoute: StudentRewardsRoute,
  TutorDashboardRoute: TutorDashboardRoute,
  TutorEarningsRoute: TutorEarningsRoute,
  TutorLessonsRoute: TutorLessonsRoute,
  TutorPaymentRequestsRoute: TutorPaymentRequestsRoute,
  AdminClassesIdRoute: AdminClassesIdRoute,
  ParentChildrenIdRoute: ParentChildrenIdRoute,
  ParentClassesIdRoute: ParentClassesIdRoute,
  AdminClassesIndexRoute: AdminClassesIndexRoute,
  ParentClassesIndexRoute: ParentClassesIndexRoute,
  TutorLessonIdReviewRoute: TutorLessonIdReviewRoute,
  TutorLessonIdIndexRoute: TutorLessonIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
